### ISSUE TITLE
Russian translation

### ISSUE THREAD

**Issue by Blueberryy** [rsedxcftvgyhbujnkiqwe/TF2-Jailbreak-From-Scratch#12]
Can i make it or plugin not ready yet for this kind of contribution?

**Comment by rsedxcftvgyhbujnkiqwe** [comment]
I welcome any translations you'd like to provide. We already have Chinese translations in the repo

**Comment by Blueberryy** [comment]
> I welcome any translations you'd like to provide. We already have Chinese translations in the repo

thanks
