### ISSUE TITLE
Grant LR not working for warden

### ISSUE THREAD

**Issue by BoozyAF** [rsedxcftvgyhbujnkiqwe/TF2-Jailbreak-From-Scratch#15]
When choosing the grant LR for player in the warden menu, it does nothing and sends an "error" in the server console. I did only have one player in the red team, but i do not think that should be causing it.
![{67915C5B-55AC-4D4F-95C1-DCB57D69EB3A}](https://github.com/user-attachments/assets/84f34fb5-601f-4c59-9c49-4a3f121cba34)

**Comment by rsedxcftvgyhbujnkiqwe** [comment]
Mistake in how the translations are handled for that entry. Although, funny enough this revealed another issue because that part in the wmenu is currently set to just spit out the usage dialogue, when instead it should just open the LR menu. I will have this fixed tomorrow.

**Comment by rsedxcftvgyhbujnkiqwe** [comment]
Fixed in [v1.3.1](https://github.com/rsedxcftvgyhbujnkiqwe/TF2-Jailbreak-From-Scratch/releases/tag/jbfs-v1.3.1)
