### ISSUE TITLE
Function query

### ISSUE THREAD

**Issue by q1085909155** [rsedxcftvgyhbujnkiqwe/TF2-Jailbreak-From-Scratch#4]
For this new version of jb plugin, I would like to ask, is there a guard weapon search function?

**Comment by rsedxcftvgyhbujnkiqwe** [comment]
There is not, but this is something I will look into adding in the next version which I am slowly working on

**Comment by q1085909155** [comment]
Thank you. I hope you can update as soon as possible. I will cancel the use of Jailbreak Redux after your next update

**Comment by rsedxcftvgyhbujnkiqwe** [comment]
Not exactly fast, but I have added this functionality into the develop branch. The next release, which should be within a week or so, will have it.

**Comment by rsedxcftvgyhbujnkiqwe** [comment]
Version 1.2 contains this feature.

On a side note, if you'd like to add chinese translations to the multitude of new phrases I added, I will merge them and generate a new release.
